language: node_js
node_js:
  - "12.18.0"
script:
  - npm run build
install:
  - npm install -g firebase-tools
  - npm install -g @vue/cli
  - npm install -g @vue/cli-service
  - npm install

after_success:
  - firebase deploy --token $FIREBASE_TOKEN